// <auto-generated />
using System;
using LearnEnglish.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearnEnglish.Migrations
{
    [DbContext(typeof(LearnEnglishContext))]
    [Migration("20220215230521_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LearnEnglish.Models.Content", b =>
                {
                    b.Property<int>("ContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("ContentDetailID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int?>("SectionID")
                        .HasColumnType("int");

                    b.HasKey("ContentID");

                    b.HasIndex("ContentDetailID");

                    b.HasIndex("SectionID");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            ContentID = 1,
                            Category = 0,
                            CreatedDate = new DateTime(2022, 2, 16, 2, 5, 19, 982, DateTimeKind.Local).AddTicks(7017),
                            Name = "Present Perfect T.",
                            Rank = (short)0
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.ContentDetail", b =>
                {
                    b.Property<int>("ContentDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.HasKey("ContentDetailID");

                    b.ToTable("ContentDetails");

                    b.HasData(
                        new
                        {
                            ContentDetailID = 1,
                            ContentType = 0,
                            CreatedDate = new DateTime(2022, 2, 16, 2, 5, 19, 982, DateTimeKind.Local).AddTicks(9465),
                            Name = "Instruction 1",
                            Rank = (short)0
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.Instruction", b =>
                {
                    b.Property<int>("InstructionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ContentDetailID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructionID");

                    b.HasIndex("ContentDetailID");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionID = 1,
                            CreatedDate = new DateTime(2022, 2, 16, 2, 5, 19, 983, DateTimeKind.Local).AddTicks(1918),
                            Info = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras laoreet pharetra tortor. Curabitur sed ante at urna interdum viverra in id augue. Fusce ligula est, imperdiet in ipsum at, varius volutpat quam. Cras ac arcu semper, condimentum massa eget, gravida orci. Morbi cursus leo vitae mi malesuada dignissim. Phasellus pellentesque massa lobortis ex vestibulum ultrices. Praesent posuere quis elit at euismod. Cras vel sem quis ipsum consequat lobortis. Pellentesque tristique elementum enim sit amet ultricies. Etiam in elit sed metus placerat blandit. Aenean ut faucibus enim. In at feugiat dolor. Donec eu euismod elit, quis maximus erat. Integer at ultrices tortor. Etiam aliquam odio tellus, vel ullamcorper velit tempus in. Curabitur iaculis libero sem, nec laoreet augue rutrum vitae. ",
                            Rank = (short)0,
                            Title = "Present Perfect Tense Title"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.Section", b =>
                {
                    b.Property<int>("SectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<int?>("ThemeID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionID");

                    b.HasIndex("ThemeID");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionID = 1,
                            CreatedDate = new DateTime(2022, 2, 16, 2, 5, 19, 982, DateTimeKind.Local).AddTicks(4647),
                            Rank = (short)0,
                            Title = "1A"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.Theme", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("IsActive")
                        .HasColumnType("smallint");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<short>("Rank")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThemeID");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            ThemeID = 1,
                            CreatedDate = new DateTime(2022, 2, 16, 2, 5, 19, 979, DateTimeKind.Local).AddTicks(2316),
                            IsActive = (short)1,
                            Level = 0,
                            Rank = (short)0,
                            Title = "Theme-1"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.Content", b =>
                {
                    b.HasOne("LearnEnglish.Models.ContentDetail", "ContentDetail")
                        .WithMany()
                        .HasForeignKey("ContentDetailID");

                    b.HasOne("LearnEnglish.Models.Section", "Section")
                        .WithMany("Contents")
                        .HasForeignKey("SectionID");

                    b.Navigation("ContentDetail");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("LearnEnglish.Models.Instruction", b =>
                {
                    b.HasOne("LearnEnglish.Models.ContentDetail", "ContentDetail")
                        .WithMany()
                        .HasForeignKey("ContentDetailID");

                    b.Navigation("ContentDetail");
                });

            modelBuilder.Entity("LearnEnglish.Models.Section", b =>
                {
                    b.HasOne("LearnEnglish.Models.Theme", "Theme")
                        .WithMany("Sections")
                        .HasForeignKey("ThemeID");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("LearnEnglish.Models.Section", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("LearnEnglish.Models.Theme", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
