// <auto-generated />
using System;
using LearnEnglish.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearnEnglish.Migrations
{
    [DbContext(typeof(LearnEnglishContext))]
    [Migration("20221006232830_version2")]
    partial class version2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LearnEnglish.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("SectionId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryType = "GrammarTips",
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 901, DateTimeKind.Local).AddTicks(2028),
                            Name = "Grammar Tips _1",
                            Rank = (byte)0,
                            SectionId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryType = "GrammarTips",
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 901, DateTimeKind.Local).AddTicks(4524),
                            Name = "Vocabulary",
                            Rank = (byte)0,
                            SectionId = 1
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InstructionId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionActivityId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ContentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructionId");

                    b.HasIndex("QuestionActivityId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            ContentId = 1,
                            CategoryId = 1,
                            ContentType = "Instruction",
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 903, DateTimeKind.Local).AddTicks(6697),
                            Rank = (byte)0,
                            Title = "Present Perfect T."
                        },
                        new
                        {
                            ContentId = 2,
                            CategoryId = 1,
                            ContentType = "Instruction",
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 903, DateTimeKind.Local).AddTicks(8246),
                            Rank = (byte)1,
                            Title = "Conjunctions"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.Instruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("InstructionId");

                    b.ToTable("Instruction");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 902, DateTimeKind.Local).AddTicks(4059),
                            Title = "Present Perfect T. part-1"
                        },
                        new
                        {
                            InstructionId = 2,
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 902, DateTimeKind.Local).AddTicks(5068),
                            Title = "Present Perfect T. part-2"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.InstructionDetail", b =>
                {
                    b.Property<int>("InstructionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstructionId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.HasKey("InstructionDetailId");

                    b.HasIndex("InstructionId");

                    b.ToTable("InstructionDetails");
                });

            modelBuilder.Entity("LearnEnglish.Models.InstructionSound", b =>
                {
                    b.Property<int>("InstructionSoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructionId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("SoundName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoundUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructionSoundId");

                    b.HasIndex("InstructionId");

                    b.ToTable("InstructionSounds");
                });

            modelBuilder.Entity("LearnEnglish.Models.MultiGapFillingQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Answer1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionActivityId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionActivityId");

                    b.ToTable("MultiGapFillingQuestions");
                });

            modelBuilder.Entity("LearnEnglish.Models.MultipleChoiceQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuestionActivityId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionActivityId");

                    b.ToTable("MultipleChoiceQuestions");
                });

            modelBuilder.Entity("LearnEnglish.Models.QuestionActivity", b =>
                {
                    b.Property<int>("QuestionActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR(40)");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.HasKey("QuestionActivityId");

                    b.ToTable("QuestionActivity");
                });

            modelBuilder.Entity("LearnEnglish.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SectionId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            SectionId = 1,
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 899, DateTimeKind.Local).AddTicks(7703),
                            Rank = (byte)0,
                            ThemeId = 1,
                            Title = "1A"
                        },
                        new
                        {
                            SectionId = 2,
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 900, DateTimeKind.Local).AddTicks(216),
                            Rank = (byte)1,
                            ThemeId = 1,
                            Title = "2A"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.SingleGapFillingQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionActivityId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionActivityId");

                    b.ToTable("SingleGapFillingQuestions");
                });

            modelBuilder.Entity("LearnEnglish.Models.Theme", b =>
                {
                    b.Property<int>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("IsActive")
                        .HasColumnType("smallint");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ThemeId");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            ThemeId = 1,
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 893, DateTimeKind.Local).AddTicks(8366),
                            IsActive = (short)1,
                            Level = 0,
                            Rank = (byte)0,
                            Title = "Theme-1"
                        },
                        new
                        {
                            ThemeId = 2,
                            CreatedDate = new DateTime(2022, 10, 7, 1, 28, 29, 897, DateTimeKind.Local).AddTicks(964),
                            IsActive = (short)1,
                            Level = 0,
                            Rank = (byte)1,
                            Title = "Theme-2"
                        });
                });

            modelBuilder.Entity("LearnEnglish.Models.TrueFalseQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Choice2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionActivityId")
                        .HasColumnType("int");

                    b.Property<byte>("Rank")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuestionActivityId");

                    b.ToTable("TrueFalseQuestions");
                });

            modelBuilder.Entity("LearnEnglish.Models.Category", b =>
                {
                    b.HasOne("LearnEnglish.Models.Section", "Section")
                        .WithMany("Categories")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("LearnEnglish.Models.Content", b =>
                {
                    b.HasOne("LearnEnglish.Models.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnEnglish.Models.Instruction", "Instruction")
                        .WithMany()
                        .HasForeignKey("InstructionId");

                    b.HasOne("LearnEnglish.Models.QuestionActivity", "QuestionActivity")
                        .WithMany()
                        .HasForeignKey("QuestionActivityId");

                    b.Navigation("Category");

                    b.Navigation("Instruction");

                    b.Navigation("QuestionActivity");
                });

            modelBuilder.Entity("LearnEnglish.Models.InstructionDetail", b =>
                {
                    b.HasOne("LearnEnglish.Models.Instruction", "Instruction")
                        .WithMany("InstructionDetails")
                        .HasForeignKey("InstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruction");
                });

            modelBuilder.Entity("LearnEnglish.Models.InstructionSound", b =>
                {
                    b.HasOne("LearnEnglish.Models.Instruction", "Instruction")
                        .WithMany("InstructionSounds")
                        .HasForeignKey("InstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instruction");
                });

            modelBuilder.Entity("LearnEnglish.Models.MultiGapFillingQuestion", b =>
                {
                    b.HasOne("LearnEnglish.Models.QuestionActivity", "QuestionActivity")
                        .WithMany("MultiGapFillingQuestions")
                        .HasForeignKey("QuestionActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionActivity");
                });

            modelBuilder.Entity("LearnEnglish.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasOne("LearnEnglish.Models.QuestionActivity", "QuestionActivity")
                        .WithMany("MultipleChoiceQuestions")
                        .HasForeignKey("QuestionActivityId");

                    b.Navigation("QuestionActivity");
                });

            modelBuilder.Entity("LearnEnglish.Models.Section", b =>
                {
                    b.HasOne("LearnEnglish.Models.Theme", "Theme")
                        .WithMany("Sections")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("LearnEnglish.Models.SingleGapFillingQuestion", b =>
                {
                    b.HasOne("LearnEnglish.Models.QuestionActivity", "QuestionActivity")
                        .WithMany("SingleGapFillingQuestions")
                        .HasForeignKey("QuestionActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionActivity");
                });

            modelBuilder.Entity("LearnEnglish.Models.TrueFalseQuestion", b =>
                {
                    b.HasOne("LearnEnglish.Models.QuestionActivity", "QuestionActivity")
                        .WithMany("TrueFalseQuestions")
                        .HasForeignKey("QuestionActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionActivity");
                });

            modelBuilder.Entity("LearnEnglish.Models.Category", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("LearnEnglish.Models.Instruction", b =>
                {
                    b.Navigation("InstructionDetails");

                    b.Navigation("InstructionSounds");
                });

            modelBuilder.Entity("LearnEnglish.Models.QuestionActivity", b =>
                {
                    b.Navigation("MultiGapFillingQuestions");

                    b.Navigation("MultipleChoiceQuestions");

                    b.Navigation("SingleGapFillingQuestions");

                    b.Navigation("TrueFalseQuestions");
                });

            modelBuilder.Entity("LearnEnglish.Models.Section", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("LearnEnglish.Models.Theme", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
